local Config = {
    FirstRoundReward = 20,
    ReplayReward = 10,
    RollCost = 20,
    ActivityIds = { "Q01", "Q02", "Q03", "Q04", "Q05", "Q06" },
    EarningActivityIds = { Q01 = true, Q02 = true, Q03 = true, Q04 = true, Q06 = true },
    RegularFigureIds = { "BigIntoEnergy01", "BigIntoEnergy02", "BigIntoEnergy03", "BigIntoEnergy04", "BigIntoEnergy05", "BigIntoEnergy06" },
    SecretFigureId = "BigIntoEnergySecret",
    RegularProbability = 0.165,
    SecretProbability = 0.01,
    WantedGuaranteeRoll = 5,
    PhuongUsername = "Phamlet707",
    PhuongUserId = 3971290001,
    HostUsername = "IamBannedrew",
    HostUserId = 1078077474,
}

return Config
